### ISSUE TITLE
Liquid Crystal Display

### ISSUE THREAD

**Issue by monomycelium** [FourierIndustries-LLP/SSTuino_II_Core#2]
I have a Liquid Crystal Display ([I2C](https://www.gammon.com.au/forum/?id=10896)), which works with Arduino Uno. When I connect it to my SSTuino II, it cannot detect any LCDs connected to it. I expected an address like `0x27` to show up on the Serial Monitor. I am using the library from [New LiquidCrystal Library by F. Malpartida](https://github.com/fmalpartida/New-LiquidCrystal) and the [I2C Scanner Sketch](https://playground.arduino.cc/Main/I2cScanner/) from Arduino Playground. Am I doing something wrong, or is there some top-secret snippet of code which I was forbidden from getting to know?

<img width="1270" alt="No I2C Devices Found" src="https://user-images.githubusercontent.com/95113443/169541648-bb4f2bac-9efc-4afa-8f07-831bca8baf5f.png">

**Comment by d3lta-v** [comment]
Hi there! Glad that you're already experimenting with your SSTuino 😄

Could I check with you which pins you used to connect your display?

**Comment by monomycelium** [comment]
The wires are connected to the pins on the Explorer Board.

LCD I2C | SSTuino II
---|---
GND | GND
VCC | 5V
SDA | A4
SCL | A5

![LCD](https://user-images.githubusercontent.com/95113443/169640399-ab0f0778-8175-44c1-91e5-1722d3bc7b33.jpeg)

**Comment by d3lta-v** [comment]
The chip used on the SSTuino (ATmega4809) is different from the Uno (ATmega328P), and packs more advanced functionality + has more pins. A4 and A5 dedicated pins that aren't connected to the I2C bus. 

To connect to I2C, you need to use the dedicated SCL and SDA pins on the top edge of the Explorer board. Those pins are internally connected to 20 and 21 for SDA and SCL respectively. 

If you're interested in the fine details of the SSTuino II, I recommend reading the [Technical Information Document](https://github.com/FourierIndustries-LLP/SSTuino-II/blob/master/Documentation/SSTuino%20Evo%20Tech%20Details.md), it really contains a wealth of information for those who wish to explore deeper. We will update the pinout diagram to the knowledge base soon :)

**Comment by d3lta-v** [comment]
Hi there, just an update, the READMEs of official repositories as well as the Knowledge Base has fully featured pinout diagrams [here](https://github.com/FourierIndustries-LLP/SSTuino-II)!

Thanks for your helpful feedback 😃
